[build]
  publish = "public"
  command = "npm run build && npm install 'mongodb' && npm install 'node-fetch'"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
